---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-cont
spec:
  containers:
    - image: httpd
      name: httpdcontainer
      ports:
        - containerPort: 80



---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine:latest
      args:
        - sleep
        - 1d

---
apiVersion: v1
kind: Pod
metadata:
  name: nopcommerce-pod
spec:
  containers:
    - name: nopcommerce
      image: hashicorp/packer
      ports:
        - containerPort: 5000        