---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd 
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo $HOSTNAME > htdocs/hostname.html"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apaches-svc
spec:
  selector:
    app: apache2
  ports:
    - name: apache2-svc
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer







