---
apiVersion: v1
kind: Pod
metadata:
  name: spring-petclinic
spec:
  containers:
    - name: spring-petclinic
      image: bsupriya/springpetclinic
      ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Pod
metadata:
  name: spc
spec:
  containers:
    - name: spc
      image: bsupriya/springpetclinic
      ports: 
        - containerPort: 8080 