---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-deploy
  ports:
    type: LoadBalancer
     - port: 34000
       protocol: TCP
       targetPort: 8080
       